# Lab 4: MM:10
### 1. Create a nd array of size 3 x 3 x 3 and perform subtraction operation as per x axis, y axis and z axis.
### 2. Demonstrate the following on the above created nd array:
#### 1. basic indexing
#### 2. slicing
#### 3. boolean indexing
#### 4. fancy indexing
### 3. Demonstrate the use of the following universal functions:
#### 1. Trigonometric functions (atleast 2)
#### 2. Statistical Functions (atleast 2)
#### 3. Bit-twiddling Functions (atleast 2)
### 4. Download the dataset of your choice and demonstrate the following operations on it:
#### 1. Read the dataset in the form of array
#### 2. Perform any 5 nd array operations on the above dataset (for ex. reshaping, ravel, transpose, vstack, concatenate etc.)
### 5. Perform file input and output operations on nd array using save, load, savetxt and loadtxt methods.


# 1. Create a nd array of size 3 x 3 x 3 and perform subtraction operation as per x axis, y axis and z axis.

In [1]:
import numpy as np

# create a 3x3x3 numpy array
arr = np.array([[[1, 5, 6], [5, 7, 9], [7, 8, 9]],
                [[15, 22, 16], [14, 15, 18], [6, 7, 8]],
                [[13,80, 27], [21, 32, 22], [29, 21, 41]]])

# subtract along the x axis
x_subtracted = np.diff(arr, axis=0)

# subtract along the y axis
y_subtracted = np.diff(arr, axis=1)

# subtract along the z axis
z_subtracted = np.diff(arr, axis=2)inal array:")
print(arr)/

print("\nSubtracted along x axis:")
print(x_subtracted)

print("\nSubtracted along y axis:")
print(y_subtracted)

print("\nSubtracted along z axis:")
print(z_subtracted)



Original array:
[[[ 1  5  6]
  [ 5  7  9]
  [ 7  8  9]]

 [[15 22 16]
  [14 15 18]
  [ 6  7  8]]

 [[13 80 27]
  [21 32 22]
  [29 21 41]]]

Subtracted along x axis:
[[[14 17 10]
  [ 9  8  9]
  [-1 -1 -1]]

 [[-2 58 11]
  [ 7 17  4]
  [23 14 33]]]

Subtracted along y axis:
[[[  4   2   3]
  [  2   1   0]]

 [[ -1  -7   2]
  [ -8  -8 -10]]

 [[  8 -48  -5]
  [  8 -11  19]]]

Subtracted along z axis:
[[[  4   1]
  [  2   2]
  [  1   1]]

 [[  7  -6]
  [  1   3]
  [  1   1]]

 [[ 67 -53]
  [ 11 -10]
  [ -8  20]]]



# 2. Demonstrate the following on the above created nd array:¶


             ###1. basic indexing

In [2]:
# access a single element
print(arr[1, 2, 1]) 

# access an entire row
print(arr[0, 1, :])  

# access a column
print(arr[2, :, 1])  


7
[5 7 9]
[80 32 21]


            ### 2. slicing

In [3]:
# get a sub-array
print(arr[1:, 1:, 1:])  

# slice along x-axis
print(arr[1, :, :])  

# slice along y-axis
print(arr[:, 1, :])  


[[[15 18]
  [ 7  8]]

 [[32 22]
  [21 41]]]
[[15 22 16]
 [14 15 18]
 [ 6  7  8]]
[[ 5  7  9]
 [14 15 18]
 [21 32 22]]


            ###3. boolean indexing

In [4]:
# create a boolean mask
mask = arr > 10

# use the mask to get elements that satisfy the condition
print(arr[mask])  

# assign a new value to the elements that satisfy the condition
arr[mask] = 0
print(arr)  

[15 22 16 14 15 18 13 80 27 21 32 22 29 21 41]
[[[1 5 6]
  [5 7 9]
  [7 8 9]]

 [[0 0 0]
  [0 0 0]
  [6 7 8]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [5]:
# select specific elements using fancy indexing
indices = [[0, 1], [2, 0], [1, 1]]
print(arr[indices]) 

# assign a new value to the elements selected using fancy indexing
arr[indices] = 100
print(arr)  

[8 0]
[[[  1   5   6]
  [  5   7   9]
  [  7 100   9]]

 [[  0 100   0]
  [  0   0   0]
  [  6   7   8]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


C:\Users\prana\AppData\Local\Temp\ipykernel_36204\3422740146.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(arr[indices])
C:\Users\prana\AppData\Local\Temp\ipykernel_36204\3422740146.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  arr[indices] = 100


# 3. Demonstrate the use of the following universal functions:

#             1. Trigonometric functions (atleast 2)

In [6]:
# Python code to demonstrate trigonometric function
import numpy as np

# create an array of angles
angles = np.array([0, 30, 45, 60, 90, 180])

# conversion of degree into radians
# using deg2rad function
radians = np.deg2rad(angles)

# sine of angles
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(np.sin(radians))

# inverse sine of sine values
print('Inverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))

# hyperbolic sine of angles
print('Sine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(np.sinh(radians))


Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]


#           2. Statistical Functions (atleast 2

In [10]:
# Python code demonstrate statistical function
import numpy as np

# construct a weight array
weight = np.array([50, 82.5, 100, 81, 55, 73, 51, 49])

# range of weight i.e. max weight-min weight
print('Range of the weight of the students: ')
print(np.ptp(weight))

# percentile
print('Weight below which 70 % student fall: ')
print(np.percentile(weight, 70))

# mean
print('Mean weight of the students: ')
print(np.mean(weight))

# median
print('Median weight of the students: ')
print(np.median(weight))

Range of the weight of the students: 
51.0
Weight below which 70 % student fall: 
80.19999999999999
Mean weight of the students: 
67.6875
Median weight of the students: 
64.0


#               3. Bit-twiddling Functions (atleast 2)


In [9]:
# Python code to demonstrate bitwise-function
import numpy as np

# construct an array of even and odd numbers
even = np.array([1, 2, 3, 4, 5, 6, 7])
odd = np.array([0, 2, 4, 8, 10, 18, 21])

# invert or not
print('inversion of even no. array: ')
print(np.invert(even))

# left_shift
print('left_shift of even no. array: ')
print(np.left_shift(even, 1))

# right_shift
print('right_shift of even no. array: ')
print(np.right_shift(even, 1))


inversion of even no. array: 
[-2 -3 -4 -5 -6 -7 -8]
left_shift of even no. array: 
[ 2  4  6  8 10 12 14]
right_shift of even no. array: 
[0 1 1 2 2 3 3]


# 4. Download the dataset of your choice and demonstrate the following operations on it:

#      1. Read the dataset in the form of array

In [12]:
import csv
import numpy as np

data = np.genfromtxt(r'C:\Users\prana\Downloads\DEM_lab\color code1.csv', delimiter=',')



# 2. Perform any 5 nd array operations on the above dataset (for ex. reshaping, ravel, transpose, vstack, concatenate etc.)

In [19]:
reshaped_data = data.reshape((8, 1))

reshaped_data


array([[nan],
       [nan],
       [nan],
       [12.],
       [nan],
       [13.],
       [nan],
       [14.]])

In [20]:
flattened_data = data.ravel()
flattened_data


array([nan, nan, nan, 12., nan, 13., nan, 14.])

In [21]:
transposed_data = data.transpose()
transposed_data

array([[nan, nan, nan, nan],
       [nan, 12., 13., 14.]])

In [22]:
stacked_data = np.vstack((data, data))
stacked_data


array([[nan, nan],
       [nan, 12.],
       [nan, 13.],
       [nan, 14.],
       [nan, nan],
       [nan, 12.],
       [nan, 13.],
       [nan, 14.]])

In [23]:
concatenated_data = np.concatenate((data, data), axis=1)
concatenated_data


array([[nan, nan, nan, nan],
       [nan, 12., nan, 12.],
       [nan, 13., nan, 13.],
       [nan, 14., nan, 14.]])